lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

# curl -X POST -H "Content-Type: application/json" http://172.105.152.192/shop-api/login -d '{"username":"rzavala@mnc.gt","password":"test"}'
