liip_imagine:
    loaders:
        aws_s3:
            stream:
                wrapper: gaufrette://sylius_image/
                
    resolvers:
        aws_s3:
            aws_s3:
                client_config:
                    credentials:
                        key:    "%aws.s3.key%"
                        secret: "%aws.s3.secret%"
                    region: "%aws.s3.region%"
                    version: "%aws.s3.version%"
                bucket: "%aws.s3.bucket%"
                get_options:
                    Scheme: https
                put_options:
                    CacheControl: "max-age=86400"
                cache_prefix: media/cache
                
    data_loader: aws_s3
    cache: aws_s3
                
    filter_sets:
        shop_api_product_original: ~
        shop_api_product_tiny:
            filters:
                fixed:
                    width: 64
                    height: 64
                thumbnail: { size: [64, 64], mode: outbound }
        shop_api_product_small:
            filters:
                fixed:
                    width: 150
                    height: 112
                thumbnail: { size: [150, 112], mode: outbound }
        shop_api_product_medium:
            filters:
                fixed:
                    width: 260
                    height: 260
                thumbnail: { size: [260, 260], mode: outbound }
        shop_api_product_large:
            filters:
                fixed:
                    width: 550
                    height: 412
                thumbnail: { size: [550, 412], mode: outbound }

        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                fixed:
                    width: 64
                    height: 64
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_shop_product_small_thumbnail:
            filters:
                fixed:
                    width: 150
                    height: 112
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_shop_product_thumbnail:
            format: png
            filters:
                fixed:
                    width: 350
                    height: 256
                thumbnail: { size: [350, 256], mode: outbound, allow_upscale: true }
        sylius_shop_product_large_thumbnail:
            format: png
            filters:
                fixed:
                    width: 550
                    height: 412
                thumbnail: { size: [550, 412], mode: outbound, allow_upscale: true }
        sylius_shop_category_thumbnail:
            filters:
                fixed:
                    width: 879
                    height: 285
                thumbnail: { size: [879, 285], mode: outbound, allow_upscale: true }
        sylius_shop_sub_category_thumbnail:
            quality: 100
            format: png
            filters:
                fixed:
                    width: 350
                    height: 256
                thumbnail: { size: [350, 256], mode: outbound, allow_upscale: true }
        sylius_shop_location_thumbnail:
            filters:
                fixed:
                    width: 296
                    height: 216
                thumbnail: { size: [296, 216], mode: outbound, allow_upscale: true }
        sylius_shop_large_thumbnail:
            filters:
                fixed:
                    width: 375
                    height: 500
                thumbnail: { size: [375, 500], mode: outbound, allow_upscale: true }
        sylius_shop_thumbnail:
            filters:
                fixed:
                    width: 480
                    height: 320
                thumbnail: { size: [480, 320], mode: outbound, allow_upscale: true }
                
        mobile_standard_thumbnail:
            filters:
                fixed:
                    width: 600
                    height: 400
                thumbnail: { size: [600, 400], mode: outbound, allow_upscale: true }
                
