liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        shop_api_product_original: ~
        shop_api_product_tiny:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        shop_api_product_small:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        shop_api_product_medium:
            filters:
                thumbnail: { size: [260, 260], mode: outbound }
        shop_api_product_large:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }
