liip_imagine:
    loaders:
        aws_s3:
            stream:
                wrapper: gaufrette://sylius_image/
                
    resolvers:
        aws_s3:
            aws_s3:
                client_config:
                    credentials:
                        key:    "%aws.s3.key%"
                        secret: "%aws.s3.secret%"
                    region: "%aws.s3.region%"
                    version: "%aws.s3.version%"
                bucket: "%aws.s3.bucket%"
                get_options:
                    Scheme: https
                put_options:
                    CacheControl: "max-age=86400"
                cache_prefix: media/cache
                
    data_loader: aws_s3
    cache: aws_s3
                
    filter_sets:
        shop_api_product_original: ~
        shop_api_product_tiny:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        shop_api_product_small:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        shop_api_product_medium:
            filters:
                thumbnail: { size: [260, 260], mode: outbound }
        shop_api_product_large:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }
        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [900, 656], mode: outbound, allow_upscale: true }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound, allow_upscale: true }
        sylius_shop_category_thumbnail:
            filters:
                thumbnail: { size: [879, 285], mode: outbound, allow_upscale: true }
        sylius_shop_sub_category_thumbnail:
            filters:
                thumbnail: { size: [879, 642], mode: outbound, allow_upscale: true }
        sylius_shop_location_thumbnail:
            filters:
                thumbnail: { size: [296, 216], mode: outbound, allow_upscale: true }
        sylius_shop_large_thumbnail:
            filters:
                thumbnail: { size: [375, 500], mode: outbound, allow_upscale: true }
        sylius_shop_thumbnail:
            filters:
                thumbnail: { size: [480, 320], mode: outbound, allow_upscale: true }
                
        mobile_thumbnail:
            filters:
                thumbnail: { size: [900, 500], mode: outbound, allow_upscale: true }
                
