framework:
    messenger:
        default_bus: meathouse.command_bus
        buses:
            meathouse.command_bus:
                middleware:
                    - doctrine_transaction
                    - messenger.middleware.dispatch_after_current_bus
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: {}
        
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: sync
                    auto_setup: true
                    
            push_notification:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: push_notification
                    auto_setup: true
                
            failed:
                dsn: 'doctrine://default'
                serializer: messenger.transport.symfony_serializer
                options:
                    queue_name: failed
                    auto_setup: true
            
        routing:
            'App\Message\Sync':  async
            'App\Message\PushNotificationMessage':  push_notification

