sylius_mailer:
    sender:
        name: '%env(APP_NAME)%'
        address: no-reply@meathouse.com
    emails:
        contact_request:
            subject: sylius.emails.contact_request.subject
            template: "@SyliusShop/Email/contactRequest.html.twig"
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "@SyliusShop/Email/orderConfirmation.html.twig"
        user_registration:
            subject: sylius.emails.user_registration.subject
            template: "Email/userRegistration.html.twig"
        password_reset:
            subject: sylius.emails.user.password_reset.subject
            template: "@SyliusShop/Email/passwordReset.html.twig"
        reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: "@SyliusShop/Email/passwordReset.html.twig"
        reset_password_pin:
            subject: sylius.emails.user.password_reset.subject
            template: "@SyliusShop/Email/passwordReset.html.twig"
        verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: "@SyliusShop/Email/verification.html.twig"
            enabled: false
