sylius_mailer:
    sender:
        name: '%env(APP_NAME)%'
        address: no-reply@meathouse.com
    emails:
        api_reset_password_token:
            subject: sylius.emails.user.reset_password_token.subject
            template: "Email/ShopApi/passwordReset.html.twig"
        contact_request:
            subject: sylius.emails.contact_request.subject
            template: "@SyliusShop/Email/contactRequest.html.twig"
        order_confirmation:
            subject: sylius.emails.order_confirmation.subject
            template: "@SyliusShop/Email/orderConfirmation.html.twig"
        user_registration:
            subject: sylius.emails.user_registration.subject
            template: "Email/userRegistration.html.twig"
        password_reset:
            subject: sylius.emails.user.password_reset.subject
            template: "Email/passwordReset.html.twig"
        reset_password_token:
            subject: sylius.emails.user.password_reset.subject
            template: "Email/passwordResetToken.html.twig"
        reset_password_pin:
            subject: sylius.emails.user.password_reset.subject
            template: "Email/passwordReset.html.twig"
        verification_token:
            subject: sylius.emails.user.verification_token.subject
            template: "@SyliusShop/Email/verification.html.twig"
            enabled: false
        message_received:
            subject: app.email.contact_us.message_received
            template: "Email/contactUs/received.html.twig"
            enabled: true
        message_sent:
            subject: app.email.contact_us.message_sent
            template: "Email/contactUs/sent.html.twig"
            enabled: true
        admin_forgot_password_request_token:
            subject: app.email.admin_password_request
            template: "Email/admin/password_request_token.html.twig"
            enabled: true
