zenstruck_schedule:
    # The default timezone for tasks (override at task level), null for system default
    timezone:             America/Guatemala

    schedule_extensions:
        email_on_failure:
            to: rzavala@praga.ws # optional if configured
            subject: ~ # optional, leave empty to use default

    mailer:
        enabled:              true

        # The mailer service to use
        service:              mailer

        # The default "from" email address (use if no mailer default from is configured)
        default_from:         rzavala@praga.ws

        # The default "to" email address (can be overridden by extension)
        default_to:           rzavala@praga.ws

        # The prefix to use for email subjects (use to distinguish between different application schedules)
        subject_prefix:       "[MeatHouse Ecommerce]" # Example: "[Acme Inc Website]"
