version: '3'

networks:
    mh-faq-net:

services:
    nginx-mh-fac:
        image: nginx:stable-alpine
        container_name: nginx-mh-fac
        ports: 
            - "8083:81"
        volumes: 
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-mh-fac
            - mysql-mh-fac
        networks:
            - mh-faq-net
    mysql-mh-fac:
        image: mysql:5.7.22
        volumes:
            - ./meathousedump.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
            - meathousedumpDB:/var/lib/mysql
        container_name: mysql-mh-fac
        restart: unless-stopped
        tty: true
        ports: 
            - "33009:3306"
        environment: 
            MYSQL_DATABASE: mhs
            MYSQL_USER: mhs
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD: mhs
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - mh-faq-net
    php-mh-fac:
        environment:
            - COMPOSER_MEMORY_LIMIT=-1 //-1 means unlimited
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                UID: $U_ID
        container_name: php-mh-fac
        volumes: 
            - ./:/var/www
            - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
        ports: 
            - "9011:9000"
        networks:
            - mh-faq-net
volumes:
  meathousedumpDB: {}