Sylius\Component\Addressing\Model\Address:
    properties:
        firstName:
            -   NotBlank:
                    groups: ['app_address']
        phoneNumber:
            - NotBlank:
                  groups: ['app_address']
