hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

facebook:
    path: /login/check-facebook

meathouse_admin:
    resource: "Controller/Admin"
    type:     annotation
    prefix:   /admin
    
meathouse_frontend:
    resource: "Controller/Frontend"
    type:     annotation
    prefix:   /store
    
meathouse_admin_api:
    resource: "Controller/AdminApi"
    type:     annotation
    prefix:   /api/v{version}
    defaults:
      _format: json
      
meathouse_shop_api:
    resource: "Controller/ShopApi"
    type:     annotation
    prefix:   /shop-api
    defaults:
        _format: json
      
meathouse_frontend_api:
    resource: "Controller/FrontendApi"
    type:     annotation
    prefix:   /store/api/v{version}
    defaults:
        _format: json
      
user_favorites:
    path: /account/favorites
    methods: [GET]
    defaults:
        _controller: app.controller.shop.extender:favoritesAction

sylius_shop_login:
    path: /store/login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: "@SyliusShop/login.html.twig"
            logged_in_route: sylius_shop_homepage
        
sylius_shop_new_password:
    path: /store/new-login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: "/frontend/newLogin.html.twig"
            logged_in_route: sylius_shop_homepage
            
sylius_shop_register_to_checkout:
    path: /store/register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect: sylius_shop_checkout_start
    
sylius_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect: store_welcome
            flash: sylius.customer.register
            
sylius_shop_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: store_set_token

sylius_shop_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: sylius_shop_new_password
    
sylius_shop_account_change_password:
    path: /account/change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:changePasswordAction
        _sylius:
            template: "@SyliusShop/Account/changePassword.html.twig"
            redirect:
                method: GET
