hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

facebook:
    path: /login/check-facebook

meathouse_admin:
    resource: "Controller/Admin"
    type:     annotation
    prefix:   /admin
    
meathouse_frontend:
    resource: "Controller/Frontend"
    type:     annotation
    prefix:   /store
    
meathouse_admin_api:
    resource: "Controller/AdminApi"
    type:     annotation
    prefix:   /api/v{version}
    defaults:
      _format: json
    
sylius_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: store_welcome
            flash: sylius.customer.register
            
sylius_shop_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: store_set_token

sylius_shop_account_change_password:
    path: /account/change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:changePasswordAction
        _sylius:
            template: "@SyliusShop/Account/changePassword.html.twig"
            redirect:
                method: GET
